---

- name: Validate OS version requirements.
  assert:
    that:
      - ansible_distribution_major_version > "6"
    fail_msg: "Only RedHat 7 and newer are supported."
    success_msg: "OS major version supported."
  when:
    - not uninstall
    - ansible_os_family == "RedHat"

- name: Install documented dependencies.
  package:
    name:
      - curl
      - unzip
    state: present
  when: not uninstall
  tags:
    - install
    - dependencies

- name: Install undocumented dependencies for EL 8.
  dnf:
    name:
      - audispd-plugins
    state: present
  when:
    - not uninstall
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"
  tags:
    - install
    - dependencies

- name: Install documented Debian dependencies.
  apt:
    name:
      - apt-transport-https
      - libplist-utils
      - python3-apt
      - gnupg
      - python3-gi
      - python3-pydbus
    state: present
  when:
    - not uninstall
    - ansible_os_family == "Debian"
  tags:
    - install
    - dependencies

- name: Setup packages.microsoft.com repository.
  include_tasks: repository.yml

- name: Install intune portal app
  apt:
    name:
      - intune-portal
    state: present
  when:
    - not uninstall
    - ansible_os_family == "Debian"
  tags:
    - install
    - dependencies
