---

- name: Manage Defender package from Microsoft repository.
  package:
    name:
      - mdatp
      - mde-netfilter
    state: "{{ uninstall | ternary ('absent', 'present') }}"
  tags:
    - package
